-- ============================================================================
-- GIGRILLA DATABASE SEEDS - TAXONOMY DATA
-- ============================================================================
-- Initial seed data for service categories, types, and user classifications

-- Service Categories
INSERT INTO service_categories (name, description) VALUES
('Accounting & Tax', 'Financial and tax-related services for the music industry'),
('Artist / Booking / Tour Management', 'Management and booking services for artists'),
('Coaching & Development', 'Professional development and coaching services'),
('Event Hospitality', 'Hospitality and catering services for events'),
('Event Production', 'Production and technical services for events'),
('Event Safety & Security', 'Safety and security services for events'),
('Freight & Logistics', 'Transportation and logistics services'),
('Funding, Finance & Insurance', 'Financial services and insurance'),
('Instrument & Equipment Hire & Repair', 'Equipment rental and repair services'),
('Media Company', 'Media production and broadcasting services'),
('Music Distribution Service', 'Music distribution and publishing services'),
('Music Education', 'Education and training services'),
('Music Law & Legal Advice', 'Legal services for the music industry'),
('Music Publishing Service', 'Publishing and rights management services'),
('Music Registration (Charts; Rights; Royalties)', 'Registration and rights services'),
('Promotion & Branding', 'Marketing and branding services'),
('Record Label Service', 'Record label and artist development services'),
('Studios & Production', 'Recording studio and production services'),
('Sync Licensing', 'Music licensing for media and advertising'),
('Travel & Accommodation', 'Travel and accommodation services');

-- Service Types (linking to categories)
INSERT INTO service_types (category_id, name, description) VALUES
(1, 'Accountancy Business', 'Accounting services'),
(1, 'Bookkeeping Business', 'Bookkeeping services'),
(1, 'Tax Advice Business', 'Tax consultation services'),
(2, 'Artist Management Business', 'Artist management services'),
(2, 'Booking Agency Business', 'Artist booking services'),
(2, 'Personal Assistant Business', 'Personal assistance services'),
(3, 'Branding & Styling Coaching Business', 'Branding coaching'),
(3, 'Motivational & Lifestyle Coaching Business', 'Motivational coaching'),
(4, 'Event Catering Business', 'Event catering services'),
(5, 'Event Design Business', 'Event design services'),
(6, 'CCTV Security Business', 'Security camera services'),
(7, 'Air Cargo Business', 'Air freight services'),
(8, 'Angel Investors', 'Investment services'),
(9, 'All Musical Instrument Hire Business', 'Instrument rental'),
(10, 'Media Broadcast Network', 'Broadcasting services'),
(11, 'Independent Distribution Partner', 'Music distribution'),
(12, 'Music School', 'Music education'),
(13, 'Commercial Law Firm', 'Legal services'),
(14, 'Independent Music Publisher', 'Publishing services'),
(15, 'Chart Organisation', 'Chart services'),
(16, 'Advertising Buying Business', 'Advertising services'),
(17, 'Independent Label', 'Record label services'),
(18, 'Mixing & Mastering Service', 'Audio production'),
(19, 'Advertising Sync Licensing Agency', 'Sync licensing'),
(20, 'Accommodation Agency', 'Accommodation services');

-- Genres
INSERT INTO genres (name, parent_id) VALUES
('Rock', NULL),
('Alternative Rock', 1),
('Classic Rock', 1),
('Indie Rock', 1),
('Pop', NULL),
('Pop Rock', 5),
('Synth Pop', 5),
('Hip Hop', NULL),
('Rap', 8),
('Trap', 8),
('Electronic', NULL),
('House', 11),
('Techno', 11),
('Jazz', NULL),
('Blues', NULL),
('Country', NULL),
('Folk', NULL),
('Classical', NULL),
('Reggae', NULL),
('R&B', NULL),
('Soul', 20),
('Funk', NULL),
('Disco', NULL),
('Punk', NULL),
('Metal', NULL),
('Heavy Metal', 25),
('Thrash Metal', 25),
('Gospel', NULL),
('World Music', NULL),
('Latin', 29),
('Afrobeat', 29),
('Experimental', NULL),
('Ambient', 32),
('Noise', 32),
('Soundtrack', NULL),
('Video Game Music', 35);

-- Moods
INSERT INTO moods (name) VALUES
('Energetic'),
('Calm'),
('Happy'),
('Sad'),
('Aggressive'),
('Romantic'),
('Mysterious'),
('Nostalgic'),
('Peaceful'),
('Intense'),
('Playful'),
('Dark'),
('Uplifting'),
('Melancholic'),
('Triumphant'),
('Dreamy'),
('Angry'),
('Hopeful'),
('Anxious'),
('Confident'),
('Lonely'),
('Joyful'),
('Tense'),
('Relaxed'),
('Excited'),
('Bittersweet'),
('Epic'),
('Intimate'),
('Chaotic'),
('Serene');

-- Update version
UPDATE db_version SET version = 2, description = 'Added taxonomy seed data' WHERE version = 1;

