'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { Video, Trash2, Play, Youtube, Settings, Loader2, Plus } from 'lucide-react'
import Image from 'next/image'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Badge } from '../../components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../components/ui/dialog'
import { YouTubeVideoModal } from '../../components/ui/youtube-video-modal'
import { addYouTubeRelParam } from '../../../lib/utils'

interface VideoItem {
  id: string
  title: string
  video_url: string
  thumbnail_url: string | null
  video_type: string
  is_featured: boolean
  sort_order: number
  created_at: string
  updated_at?: string | null
}

export function ArtistVideosManager() {
  const [videos, setVideos] = useState<VideoItem[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const [newYoutubeUrl, setNewYoutubeUrl] = useState('')
  const [newVideoTitle, setNewVideoTitle] = useState('')
  const [previewThumbnail, setPreviewThumbnail] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false)
  const [metadataLoading, setMetadataLoading] = useState(false)
  const [metadataError, setMetadataError] = useState<string | null>(null)
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState<string | null>(null)
  const autoTitleRef = useRef<string | null>(null)

  // Manage dialog state
  const [manageDialogOpen, setManageDialogOpen] = useState(false)
  const [selectedVideo, setSelectedVideo] = useState<VideoItem | null>(null)
  const [editTitle, setEditTitle] = useState('')

  // Video modal state
  const [videoModalOpen, setVideoModalOpen] = useState(false)
  const [modalVideoUrl, setModalVideoUrl] = useState<string | null>(null)

  const extractVideoId = useCallback((url: string): string | null => {
    const match = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([^&\n?#]+)/)
    return match ? match[1] : null
  }, [])

  const fetchVideos = useCallback(async () => {
    try {
      setLoading(true)
      const response = await fetch('/api/artist-videos')
      const result = await response.json()

      if (result.error) {
        setError(result.error)
        return
      }

      setVideos(result.data || [])
      setError(null)
    } catch (err) {
      console.error('Failed to fetch videos:', err)
      setError('Failed to load videos')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchVideos()
  }, [fetchVideos])

  // Update preview when URL changes
  useEffect(() => {
    const videoId = extractVideoId(newYoutubeUrl)

    if (!videoId) {
      setPreviewThumbnail(null)
      autoTitleRef.current = null
      setAutoGeneratedTitle(null)
      setMetadataError(null)
      setMetadataLoading(false)
      return
    }

    setPreviewThumbnail(`https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`)

    const controller = new AbortController()
    const timeoutId = setTimeout(async () => {
      setMetadataLoading(true)
      setMetadataError(null)

      try {
        const response = await fetch(
          `https://www.youtube.com/oembed?url=${encodeURIComponent(newYoutubeUrl)}&format=json`,
          { signal: controller.signal }
        )

        if (!response.ok) {
          throw new Error('Failed to fetch metadata')
        }

        const data = await response.json()
        if (controller.signal.aborted) return

        const previousAutoTitle = autoTitleRef.current
        autoTitleRef.current = data.title
        setAutoGeneratedTitle(data.title)
        setNewVideoTitle(prev => {
          if (!prev.trim() || prev === previousAutoTitle) {
            return data.title
          }
          return prev
        })
      } catch (err) {
        if (controller.signal.aborted) return
        console.error('Failed to fetch YouTube metadata:', err)
        autoTitleRef.current = null
        setAutoGeneratedTitle(null)
        setMetadataError('Unable to fetch title from YouTube. Please enter it manually.')
      } finally {
        if (!controller.signal.aborted) {
          setMetadataLoading(false)
        }
      }
    }, 400)

    return () => {
      controller.abort()
      clearTimeout(timeoutId)
    }
  }, [newYoutubeUrl, extractVideoId])

  const handleUploadVideo = async () => {
    if (!newYoutubeUrl.trim() || !newVideoTitle.trim()) return

    const videoId = extractVideoId(newYoutubeUrl)
    if (!videoId) {
      setError('Invalid YouTube URL. Please use a valid YouTube link.')
      return
    }

    setUploading(true)
    setError(null)

    try {
      // Add &rel=0 to prevent suggested videos
      const urlWithRelParam = addYouTubeRelParam(newYoutubeUrl.trim())

      const response = await fetch('/api/artist-videos', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newVideoTitle.trim(),
          video_url: urlWithRelParam,
          thumbnail_url: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`
        })
      })

      const result = await response.json()

      if (result.error) {
        setError(result.error)
        return
      }

      // Add to local state
      setVideos(prev => [...prev, result.data])
      setNewYoutubeUrl('')
      setNewVideoTitle('')
      setPreviewThumbnail(null)
    } catch (err) {
      console.error('Failed to upload video:', err)
      setError('Failed to upload video')
    } finally {
      setUploading(false)
    }
  }

  const handleDeleteVideo = async (id: string) => {
    if (!confirm('Are you sure you want to delete this video?')) return

    try {
      const response = await fetch(`/api/artist-videos?id=${id}`, {
        method: 'DELETE'
      })

      const result = await response.json()

      if (result.error) {
        setError(result.error)
        return
      }

      setVideos(prev => prev.filter(v => v.id !== id))
      setManageDialogOpen(false)
      setSelectedVideo(null)
    } catch (err) {
      console.error('Failed to delete video:', err)
      setError('Failed to delete video')
    }
  }

  const handleUpdateVideo = async () => {
    if (!selectedVideo || !editTitle.trim()) return

    setSaving(true)

    try {
      const response = await fetch('/api/artist-videos', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: selectedVideo.id,
          title: editTitle.trim()
        })
      })

      const result = await response.json()

      if (result.error) {
        setError(result.error)
        return
      }

      setVideos(prev => prev.map(v => 
        v.id === selectedVideo.id ? { ...v, title: editTitle.trim() } : v
      ))
      setManageDialogOpen(false)
      setSelectedVideo(null)
    } catch (err) {
      console.error('Failed to update video:', err)
      setError('Failed to update video')
    } finally {
      setSaving(false)
    }
  }

  const openManageDialog = (video: VideoItem) => {
    setSelectedVideo(video)
    setEditTitle(video.title)
    setManageDialogOpen(true)
  }

  const handlePlayVideo = (videoUrl: string) => {
    setModalVideoUrl(videoUrl)
    setVideoModalOpen(true)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-purple-600" />
      </div>
    )
  }

  const totalVideos = videos.length
  const featuredCount = videos.filter(video => video.is_featured).length
  const lastUpdatedTimestamp = videos.length
    ? Math.max(...videos.map(video => new Date(video.updated_at || video.created_at).getTime()))
    : null
  const lastUpdatedLabel = lastUpdatedTimestamp
    ? new Date(lastUpdatedTimestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
    : 'Not yet added'

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-xl bg-gradient-to-r from-purple-600 via-fuchsia-600 to-orange-500 text-white p-6 shadow-lg">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-white/80">Artist Showcase</p>
            <h1 className="text-2xl font-semibold mt-1">Profile Videos</h1>
          </div>
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-white/20 flex items-center justify-center">
              <Youtube className="w-5 h-5 text-white" />
            </div>
            <p className="text-sm text-white/80 max-w-xs">
              Paste your YouTube performances to elevate your public artist page.
            </p>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs text-gray-500 uppercase tracking-wide">Total Videos</p>
          <p className="text-2xl font-semibold text-gray-900 mt-1">{totalVideos}</p>
          <p className="text-xs text-gray-500 mt-1">
            {totalVideos > 0 ? 'You’re building a strong reel.' : 'Add your first video to get started.'}
          </p>
        </div>
        <div className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs text-gray-500 uppercase tracking-wide">Featured Spotlights</p>
          <p className="text-2xl font-semibold text-gray-900 mt-1">{featuredCount}</p>
          <p className="text-xs text-gray-500 mt-1">
            Highlight best performances in your fan-facing experience.
          </p>
        </div>
        <div className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs text-gray-500 uppercase tracking-wide">Last Update</p>
          <p className="text-xl font-semibold text-gray-900 mt-1">{lastUpdatedLabel}</p>
          <p className="text-xs text-gray-500 mt-1">Keep this section fresh with new performances.</p>
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-sm text-red-600">{error}</p>
          <button 
            onClick={() => setError(null)}
            className="text-xs text-red-500 underline mt-1"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Upload Section */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
        <div className="mb-6">
          <div className="flex items-center space-x-2 mb-2">
            <Youtube className="w-5 h-5 text-red-600" />
            <h2 className="text-lg font-semibold text-gray-900">Add Your Artist Profile Videos</h2>
          </div>
          <p className="text-gray-500 text-sm">
            These are Artist Profile videos to showcase your performances. Links must be YouTube Embed Links.
          </p>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-[1.1fr,0.9fr] gap-6">
          {/* Input Form */}
          <div className="space-y-4">
            <div className="rounded-xl border border-gray-200 p-4">
              <label className="block text-sm font-medium text-gray-900 mb-1">
                Paste a YouTube Link
              </label>
              <p className="text-xs text-gray-500 mb-3">
                Standard or shortened URLs both work. We’ll grab the preview automatically.
              </p>
              <Input
                value={newYoutubeUrl}
                onChange={(e) => setNewYoutubeUrl(e.target.value)}
                placeholder="https://youtu.be/your-video"
                className="text-sm"
              />
            </div>

            <div className="rounded-xl border border-gray-200 p-4 space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-gray-900">
                  Video Title
                </label>
                {autoGeneratedTitle && newVideoTitle === autoGeneratedTitle && !metadataLoading && (
                  <span className="text-xs text-green-600 font-medium">Auto-filled</span>
                )}
              </div>
              <Input
                value={newVideoTitle}
                onChange={(e) => setNewVideoTitle(e.target.value)}
                placeholder="Enter a title or keep the YouTube title"
                className="text-sm"
              />
              <div className="text-xs text-gray-500 min-h-[1rem]">
                {metadataLoading && 'Fetching title from YouTube…'}
                {metadataError && <span className="text-red-500">{metadataError}</span>}
              </div>
            </div>

            <div className="flex flex-col gap-3 sm:flex-row">
              <Button
                onClick={handleUploadVideo}
                className="flex-1 bg-purple-600 hover:bg-purple-700 text-white shadow-sm"
                disabled={!newYoutubeUrl.trim() || !newVideoTitle.trim() || uploading}
              >
                {uploading ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Adding...
                  </>
                ) : (
                  <>
                    <Plus className="w-4 h-4 mr-2" />
                    Add Video
                  </>
                )}
              </Button>
              <Button
                type="button"
                variant="outline"
                className="flex-1 border-dashed"
                onClick={() => {
                  setNewYoutubeUrl('')
                  setNewVideoTitle('')
                  setPreviewThumbnail(null)
                  setMetadataError(null)
                  setAutoGeneratedTitle(null)
                }}
                disabled={uploading && !newYoutubeUrl}
              >
                Clear
              </Button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="rounded-lg border border-purple-100 bg-purple-50 p-3">
                <p className="text-xs font-semibold text-purple-700 uppercase tracking-wide">Tip</p>
                <p className="text-sm text-purple-900 mt-1">
                  Use live performance clips between 20s–3mins for the best engagement.
                </p>
              </div>
              <div className="rounded-lg border border-blue-100 bg-blue-50 p-3">
                <p className="text-xs font-semibold text-blue-700 uppercase tracking-wide">Supported</p>
                <p className="text-sm text-blue-900 mt-1">youtube.com &amp; youtu.be links are both accepted.</p>
              </div>
            </div>
          </div>

          {/* Preview Area */}
          <div className="space-y-4">
            <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs font-semibold text-gray-600 uppercase tracking-wide">Live Preview</p>
                {previewThumbnail && (
                  <span className="text-xs text-gray-500">
                    {newVideoTitle ? `${newVideoTitle.length}/80 chars` : 'Waiting for title'}
                  </span>
                )}
              </div>

              {previewThumbnail ? (
                <div className="aspect-video bg-gray-200 rounded-lg overflow-hidden relative">
                  <Image
                    src={previewThumbnail}
                    alt="Video preview"
                    fill
                    sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw"
                    className="object-cover"
                    onError={() => setPreviewThumbnail(null)}
                  />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-14 h-14 bg-white/90 rounded-full flex items-center justify-center shadow-lg">
                      <Play className="w-7 h-7 text-gray-900 ml-1" />
                    </div>
                  </div>
                </div>
              ) : (
                <div className="aspect-video flex flex-col items-center justify-center rounded-lg border border-dashed border-gray-300 bg-white">
                  <Video className="w-10 h-10 text-gray-300 mb-2" />
                  <p className="text-sm text-gray-500">Paste a link to generate a preview.</p>
                </div>
              )}

              {newVideoTitle && (
                <p className="mt-3 text-sm font-medium text-gray-900 truncate">{newVideoTitle}</p>
              )}
            </div>

            <div className="rounded-xl border border-gray-200 p-4 bg-white">
              <p className="text-xs uppercase tracking-wide text-gray-500 mb-2">Best Practices</p>
              <ul className="space-y-2 text-sm text-gray-600">
                <li className="flex items-start gap-2">
                  <span className="mt-1 h-1.5 w-1.5 rounded-full bg-purple-500" />
                  Ensure the video is set to public or unlisted.
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1 h-1.5 w-1.5 rounded-full bg-purple-500" />
                  Use descriptive titles to help bookers know what they’re watching.
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1 h-1.5 w-1.5 rounded-full bg-purple-500" />
                  Mix highlight reels with intimate live moments for range.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* Videos Grid */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-2">
            <h2 className="text-lg font-semibold text-gray-900">Your Artist Videos</h2>
            <Badge variant="outline" className="text-xs">
              {videos.length} video{videos.length !== 1 ? 's' : ''}
            </Badge>
          </div>
        </div>

        {videos.length === 0 ? (
          <div className="text-center py-12 bg-gray-50 rounded-lg">
            <Video className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500 text-sm">No videos uploaded yet</p>
            <p className="text-gray-400 text-xs mt-1">Videos will appear here once uploaded</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-5">
            {videos.map((video) => {
              const videoId = extractVideoId(video.video_url)
              const thumbnail = video.thumbnail_url || (videoId ? `https://img.youtube.com/vi/${videoId}/mqdefault.jpg` : null)

              return (
                <div key={video.id} className="group rounded-2xl border border-gray-100 shadow-sm overflow-hidden bg-white flex flex-col">
                  <div
                    className="aspect-video bg-gray-100 relative cursor-pointer"
                    onClick={() => handlePlayVideo(video.video_url)}
                  >
                    {thumbnail ? (
                      <Image
                        src={thumbnail}
                        alt={video.title}
                        fill
                        sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw"
                        className="object-cover"
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center bg-gray-200">
                        <Video className="w-8 h-8 text-gray-400" />
                      </div>
                    )}
                    <div className="absolute inset-0 flex items-center justify-center transition">
                      <div className="w-10 h-10 bg-white/90 rounded-full flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform">
                        <Play className="w-5 h-5 text-gray-900 ml-0.5" />
                      </div>
                    </div>
                    {video.is_featured && (
                      <span className="absolute top-3 left-3 rounded-full bg-white/90 px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-purple-700 shadow">
                        Featured
                      </span>
                    )}
                  </div>

                  {/* Video info */}
                  <div className="p-4 flex flex-col flex-1">
                    <p className="text-sm font-semibold text-gray-900 line-clamp-2">{video.title}</p>
                    <p className="text-xs text-gray-500 mt-1">
                      Added {new Date(video.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                    </p>
                    <div className="mt-auto">
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full mt-3 text-xs"
                        onClick={() => openManageDialog(video)}
                      >
                        <Settings className="w-3 h-3 mr-1" />
                        Manage Video
                      </Button>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* Manage Video Dialog */}
      <Dialog open={manageDialogOpen} onOpenChange={setManageDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="text-lg font-semibold text-gray-900">Manage Video</DialogTitle>
            <DialogDescription>Update the title, review details, or remove the video.</DialogDescription>
          </DialogHeader>

          <div className="space-y-5">
            {selectedVideo && (
              <div className="rounded-xl border border-gray-200 overflow-hidden">
                <div className="aspect-video relative bg-gray-100">
                  <Image
                    src={
                      selectedVideo.thumbnail_url ||
                      (extractVideoId(selectedVideo.video_url)
                        ? `https://img.youtube.com/vi/${extractVideoId(selectedVideo.video_url)}/mqdefault.jpg`
                        : '/placeholder.png')
                    }
                    alt={selectedVideo.title}
                    fill
                    className="object-cover"
                  />
                  <div className="absolute inset-0 bg-black/25 flex items-center justify-center">
                    <Play className="w-8 h-8 text-white" />
                  </div>
                </div>
                <div className="p-4 text-sm text-gray-600 space-y-1">
                  <p className="font-semibold text-gray-900">{selectedVideo.title}</p>
                  <p className="text-xs text-gray-500">
                    Added {new Date(selectedVideo.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                  <a
                    href={selectedVideo.video_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-xs text-purple-600 font-medium"
                  >
                    View on YouTube
                  </a>
                </div>
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Video Title
              </label>
              <Input
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                placeholder="Enter a title"
              />
            </div>
          </div>

          <DialogFooter className="flex flex-col gap-3 sm:flex-row sm:justify-between">
            <Button
              variant="destructive"
              onClick={() => selectedVideo && handleDeleteVideo(selectedVideo.id)}
              disabled={!selectedVideo}
              className="w-full sm:w-auto"
            >
              <Trash2 className="w-4 h-4 mr-2" />
              Delete Video
            </Button>
            <Button
              onClick={handleUpdateVideo}
              disabled={saving || !editTitle.trim()}
              className="w-full sm:w-auto bg-purple-600 hover:bg-purple-700 text-white"
            >
              {saving ? (
                <>
                  <Loader2 className="w-4 h-4 mr-1 animate-spin" /> Saving
                </>
              ) : (
                'Save Changes'
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* YouTube Video Modal */}
      <YouTubeVideoModal
        videoUrl={modalVideoUrl}
        isOpen={videoModalOpen}
        onClose={() => setVideoModalOpen(false)}
      />
    </div>
  )
}
