-- Apply genre seed data
INSERT INTO genres (name, parent_id) VALUES
('Rock', NULL),
('Alternative Rock', 1),
('Classic Rock', 1),
('Indie Rock', 1),
('Pop', NULL),
('Pop Rock', 5),
('Synth Pop', 5),
('Hip Hop', NULL),
('Rap', 8),
('Trap', 8),
('Electronic', NULL),
('House', 11),
('Techno', 11),
('Jazz', NULL),
('Blues', NULL),
('Country', NULL),
('Folk', NULL),
('Classical', NULL),
('Reggae', NULL),
('R&B', NULL),
('Soul', 20),
('Funk', NULL),
('Disco', NULL),
('Punk', NULL),
('Metal', NULL),
('Heavy Metal', 25),
('Thrash Metal', 25),
('Gospel', NULL),
('World Music', NULL),
('Latin', 29),
('Afrobeat', 29),
('Experimental', NULL),
('Ambient', 32),
('Noise', 32),
('Soundtrack', NULL),
('Video Game Music', 35)
ON CONFLICT (name) DO NOTHING;
