-- Migration 059: Country Tax IDs Reference Table + Partnership Tax ID column
-- Source: FINAL SIMPLE WEB-READY Tax IDs for Gigrilla and its Members.xlsx
-- 249 countries with corporate and individual tax ID types, formats, and authorities.

-- ============================================================
-- Add partnership_tax_id to artist_payment_details
-- ============================================================
ALTER TABLE public.artist_payment_details
  ADD COLUMN IF NOT EXISTS partnership_tax_id TEXT;

COMMENT ON COLUMN public.artist_payment_details.partnership_tax_id IS 'Partnership taxpayer ID supplied for the artist entity';

-- ============================================================
-- TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.country_tax_ids (
  id                          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  country_name                TEXT        NOT NULL,
  country_code                CHAR(2)     NOT NULL UNIQUE,
  tax_authority               TEXT,
  is_unverifiable             BOOLEAN     NOT NULL DEFAULT FALSE,

  -- Generic / National Tax ID (applies to both corp and indiv in some countries)
  generic_id_corp_display     BOOLEAN     NOT NULL DEFAULT FALSE,
  generic_id_indiv_display    BOOLEAN     NOT NULL DEFAULT FALSE,
  generic_id_name             TEXT,
  generic_id_format           TEXT,

  -- Individual / Personal Tax ID
  individual_id_corp_display  BOOLEAN     NOT NULL DEFAULT FALSE,
  individual_id_indiv_display BOOLEAN     NOT NULL DEFAULT FALSE,
  individual_id_name          TEXT,
  individual_id_format        TEXT,

  -- Business / Company Tax ID
  business_id_corp_display    BOOLEAN     NOT NULL DEFAULT FALSE,
  business_id_indiv_display   BOOLEAN     NOT NULL DEFAULT FALSE,
  business_id_name            TEXT,
  business_id_format          TEXT,

  -- Partnership Tax ID
  partnership_id_corp_display  BOOLEAN    NOT NULL DEFAULT FALSE,
  partnership_id_indiv_display BOOLEAN    NOT NULL DEFAULT FALSE,
  partnership_id_name          TEXT,
  partnership_id_format        TEXT,

  -- VAT / GST / SST ID
  vat_id_corp_display         BOOLEAN     NOT NULL DEFAULT FALSE,
  vat_id_indiv_display        BOOLEAN     NOT NULL DEFAULT FALSE,
  vat_id_name                 TEXT,
  vat_id_format               TEXT,

  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_country_tax_ids_code   ON public.country_tax_ids (country_code);
CREATE INDEX IF NOT EXISTS idx_country_tax_ids_name   ON public.country_tax_ids (LOWER(country_name));

-- Public read access (reference table, no auth needed)
ALTER TABLE public.country_tax_ids ENABLE ROW LEVEL SECURITY;
CREATE POLICY "country_tax_ids_public_read"
  ON public.country_tax_ids FOR SELECT
  USING (true);

-- ============================================================
-- SEED DATA (249 countries)
-- ============================================================
INSERT INTO public.country_tax_ids (
  country_name, country_code, tax_authority, is_unverifiable,
  generic_id_corp_display, generic_id_indiv_display, generic_id_name, generic_id_format,
  individual_id_corp_display, individual_id_indiv_display, individual_id_name, individual_id_format,
  business_id_corp_display, business_id_indiv_display, business_id_name, business_id_format,
  partnership_id_corp_display, partnership_id_indiv_display, partnership_id_name, partnership_id_format,
  vat_id_corp_display, vat_id_indiv_display, vat_id_name, vat_id_format
) VALUES
  ('Afghanistan', 'AF', 'Afghanistan Revenue Department', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Åland Islands', 'AX', 'Finnish Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Identity Code', '131052-308T',
   TRUE, FALSE, 'Business ID', '1234567-8',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'ALV Number', '1234567-8'),
  ('Albania', 'AL', 'General Directorate of Taxation', FALSE,
   TRUE, TRUE, 'NIPT', 'J12345678N',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIPT', 'J12345678N'),
  ('Algeria', 'DZ', 'Directorate General of Taxes', FALSE,
   TRUE, TRUE, 'NIF', '123456789012345',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '123456789012345'),
  ('American Samoa', 'AS', 'Tax Office, American Samoa Government', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN/ITIN', '123-45-6789',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Andorra', 'AD', 'Tax and Borders Department', FALSE,
   TRUE, TRUE, 'NRT', 'A-123456-Z',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NRT', 'A-123456-Z'),
  ('Angola', 'AO', 'General Tax Administration', FALSE,
   TRUE, TRUE, 'NIF', '5123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '5123456789'),
  ('Anguilla', 'AI', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'TIN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '2234567890'),
  ('Antarctica', 'AQ', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Antigua and Barbuda', 'AG', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12345678'),
  ('Argentina', 'AR', 'Agencia de Recaudación y Control Aduanero (ARCA), provincial tax agencies', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CUIT/CUIL', '20-12345678-3',
   TRUE, FALSE, 'Business CUIT', '30-12345678-1',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Business CUIT', '30-12345678-1'),
  ('Armenia', 'AM', 'State Revenue Committee', FALSE,
   TRUE, TRUE, 'TIN', '02538904',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '02538904'),
  ('Aruba', 'AW', 'Department of Taxes', FALSE,
   TRUE, TRUE, 'TIN', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Australia', 'AU', 'Australian Taxation Office, state and territory revenue offices', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TFN', '123456789',
   TRUE, FALSE, 'ABN', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST ABN', '12345678901'),
  ('Austria', 'AT', 'Federal Ministry of Finance', FALSE,
   TRUE, TRUE, 'Steuernummer', '12-345/6789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'UID', 'ATU12345678'),
  ('Azerbaijan', 'AZ', 'State Tax Service under the Ministry of Economy of the Republic of Azerbaijan', FALSE,
   TRUE, TRUE, 'TIN', '0123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '0123456789'),
  ('Bahamas', 'BS', 'Department of Inland Revenue', FALSE,
   TRUE, TRUE, 'TIN', '123.456.789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123.456.789'),
  ('Bahrain', 'BH', 'National Bureau for Revenue', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '123 456 789 012 345'),
  ('Bangladesh', 'BD', 'National Board of Revenue', FALSE,
   TRUE, TRUE, 'TIN', '123 456 789 012',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BIN', '123456789-0123'),
  ('Barbados', 'BB', 'Barbados Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '1 123 456 789 012',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1 123 456 789 012'),
  ('Belarus', 'BY', 'Ministry for Taxes and Duties of the Republic of Belarus', FALSE,
   TRUE, TRUE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('Belgium', 'BE', 'Federal Public Service Finance, regional tax administrations', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'National Number', '12345678901',
   TRUE, FALSE, 'Enterprise Number', '0123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'BE0123456789'),
  ('Belize', 'BZ', 'Belize Tax Service Department', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST TIN', '123456'),
  ('Benin', 'BJ', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'IFU', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT IFU', '1 234 567 890 123'),
  ('Bermuda', 'BM', 'Office of the Tax Commissioner', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Bhutan', 'BT', 'Department of Revenue and Customs', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CID', '22334455667',
   TRUE, FALSE, 'TIN', '22334455667',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BST TIN', '22334455667'),
  ('Bolivia', 'BO', 'National Tax Service (Servicio de Impuestos Nacionales)', FALSE,
   TRUE, TRUE, 'NIT', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIT', '123456789'),
  ('Bonaire, Sint Eustatius and Saba', 'BQ', 'Tax and Customs Administration Caribbean Netherlands', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BSN', '1234.12.123',
   TRUE, FALSE, 'CRIB', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'ABB', '312.345.678'),
  ('Bosnia and Herzegovina', 'BA', 'Indirect Taxation Authority, Tax Administration of the Federation of Bosnia and Herzegovina, Tax Administration of Republika Srpska, Brčko District Tax Administration', FALSE,
   TRUE, TRUE, 'TIN', '123 456 789 012',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123 456 789 012'),
  ('Botswana', 'BW', 'Botswana Unified Revenue Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual TIN', 'I123456789',
   TRUE, FALSE, 'Corporate TIN', 'C01234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'C012345678901'),
  ('Bouvet Island', 'BV', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Brazil', 'BR', 'Receita Federal do Brasil, state finance secretariats, municipal finance secretariats', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CPF', '123.456.789-01',
   TRUE, FALSE, 'CNPJ', '12.345.678/0001-22, 12.ABC.345/01DE-35',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CBS, IBS // IPI, ICMS, ISS', '12.345.678/0001-22, 12.ABC.345/01DE-35'),
  ('British Indian Ocean Territory', 'IO', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Brunei', 'BN', 'Revenue Division, Ministry of Finance and Economy', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NRIC', '00-123456',
   TRUE, FALSE, 'ROCBN (RC/RFC)', 'RC2001234, RFC000123',
   FALSE, FALSE, 'ROCBN (P)', 'P12345',
   FALSE, FALSE, NULL, NULL),
  ('Bulgaria', 'BG', 'National Revenue Agency', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'EGN/LNCH', '1234567890',
   TRUE, FALSE, 'UIC', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'BG0123456789'),
  ('Burkina Faso', 'BF', 'Directorate General of Taxes', FALSE,
   TRUE, TRUE, 'IFU', '12345678A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT IFU', '12345678A'),
  ('Burundi', 'BI', 'Office Burundais des Recettes', FALSE,
   TRUE, TRUE, 'TIN/NIF', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA TIN/NIF', '1234567890'),
  ('Cabo Verde', 'CV', 'Tax and Customs Authority of Cabo Verde', FALSE,
   TRUE, TRUE, 'NIF', '213456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '213456789'),
  ('Cambodia', 'KH', 'General Department of Taxation', FALSE,
   TRUE, TRUE, 'TIN', '1001-123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1001-123456789'),
  ('Cameroon', 'CM', 'Directorate General of Taxation', FALSE,
   TRUE, TRUE, 'NIU', 'M123456789000L',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIU', 'M123456789000L'),
  ('Canada', 'CA', 'Canada Revenue Agency, Revenu Québec, provincial and territorial revenue authorities', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SIN/ITN', '123456789',
   TRUE, FALSE, 'BN', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST/HST Number, QST Number, PST Number, RST Number', '123456789RT0001; 1234567890TQ1234; PST-1234-5678; 123456-7; 1234567'),
  ('Cayman Islands', 'KY', 'Cayman Islands Customs & Border Control Service, Tax Information Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Central African Republic', 'CF', 'Direction Générale des Impôts et des Domaines', FALSE,
   TRUE, TRUE, 'NIF', '99-999/9999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '99-999/9999'),
  ('Chad', 'TD', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '1234567Z',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '1234567Z'),
  ('Chile', 'CL', 'Servicio de Impuestos Internos', FALSE,
   TRUE, TRUE, 'RUT', '12.345.678-K',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RUT', '12.345.678-K'),
  ('China', 'CN', 'State Taxation Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Resident ID Number', '123 456 789 012 345 678',
   TRUE, FALSE, 'Unified Social Credit Code', '91350211M000100Y43',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TIN', '91350211M000100Y43'),
  ('Christmas Island', 'CX', 'Australian Taxation Office', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TFN', '123456789',
   TRUE, FALSE, 'ABN', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST Number', '12345678901'),
  ('Cocos (Keeling) Islands', 'CC', 'Australian Taxation Office', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TFN', '123456789',
   TRUE, FALSE, 'ABN', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST Number', '12345678901'),
  ('Colombia', 'CO', 'Dirección de Impuestos y Aduanas Nacionales (DIAN)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Cédula', '123456789-0 / 1234567890',
   TRUE, FALSE, 'NIT', '123.456.789-0',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIT', '123.456.789-0'),
  ('Comoros', 'KM', 'Direction Générale des Impôts', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PIN', 'UnknownFormat',
   TRUE, FALSE, 'NIF', 'UnknownFormat',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA', 'UnknownFormat'),
  ('Cook Islands', 'CK', 'Revenue Management Division, Ministry of Finance and Economic Management', FALSE,
   TRUE, TRUE, 'TIN/RMD', '12345',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12345'),
  ('Costa Rica', 'CR', 'Ministerio de Hacienda', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'ID Number', '1-2345-6789',
   TRUE, FALSE, 'NITE', '1-234-567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NITE', '1-234-567890'),
  ('Côte d''Ivoire', 'CI', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'IDU', 'CIYYYY1234567A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', '1234567A'),
  ('Croatia', 'HR', 'Tax Administration, Ministry of Finance', FALSE,
   TRUE, TRUE, 'OIB', '12345678901',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'HR12345678901'),
  ('Cuba', 'CU', 'Oficina Nacional de Administración Tributaria (ONAT)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CI', '12345678901',
   TRUE, FALSE, 'NIT', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIT', '12345678901'),
  ('Curaçao', 'CW', 'Tax and Customs Administration Curaçao', FALSE,
   TRUE, TRUE, 'Persoonsnummer/TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Persoonsnummer/TIN', '123456789'),
  ('Cyprus', 'CY', 'Tax Department, Ministry of Finance', FALSE,
   TRUE, TRUE, 'TIC', '12345678L',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'CY12345678Z'),
  ('Czechia', 'CZ', 'Financial Administration of the Czech Republic', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Rodné číslo', '123456/7890',
   TRUE, FALSE, 'DIČ', 'CZ1234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'DIČ', 'CZ1234567890'),
  ('Democratic Republic of the Congo', 'CD', 'Direction Générale des Impôts', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TIN/NIF', 'A123456789',
   TRUE, FALSE, 'NIF', 'A1234567R',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA NIF', 'A1234567R'),
  ('Denmark', 'DK', 'Danish Tax Agency', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CPR Number', '123456-7890',
   TRUE, FALSE, 'CVR Number', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT CVR', 'DK12345678'),
  ('Djibouti', 'DJ', 'Direction des Impôts', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal TIN/NIF', '1234567892',
   TRUE, FALSE, 'Business TIN/NIF', '1234567891',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', '1234567891'),
  ('Dominica', 'DM', 'Inland Revenue Division', FALSE,
   TRUE, TRUE, 'TIN', '1234567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567'),
  ('Dominican Republic', 'DO', 'Dirección General de Impuestos Internos (DGII)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Cédula/RNC', '001-1234567-8 / 123-4567890-1',
   TRUE, FALSE, 'RNC', '123-4567890-1',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'RNC', '123-4567890-1'),
  ('Ecuador', 'EC', 'Servicio de Rentas Internas (SRI)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Cédula', '1234567890',
   TRUE, FALSE, 'RUC', '1 234 567 890 001',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'RUC', '1 234 567 890 001'),
  ('Egypt', 'EG', 'Egyptian Tax Authority', FALSE,
   TRUE, TRUE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('El Salvador', 'SV', 'Ministry of Finance, Dirección General de Impuestos Internos', FALSE,
   TRUE, TRUE, 'NIT', '1234-567890-123-4',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIT', '1234-567890-123-4'),
  ('Equatorial Guinea', 'GQ', 'Dirección General de Impuestos y Contribuciones', FALSE,
   TRUE, TRUE, 'TIN/NIF', 'XXXXXXXXXXXXXXXX (alphanumeric up to 16 characters long)',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IVA/VAT Number', '123, 1'),
  ('Eritrea', 'ER', 'Inland Revenue Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal TIN', '187654321-0',
   TRUE, FALSE, 'Business TIN', '287654321-0',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax TIN', '287654321-0'),
  ('Estonia', 'EE', 'Estonian Tax and Customs Board', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Identification Code', '12345678901',
   TRUE, FALSE, 'Registry Code', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'KMKR', 'EE123456789'),
  ('Eswatini', 'SZ', 'Eswatini Revenue Service', FALSE,
   TRUE, TRUE, 'TIN', '123-456-789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123-456-789'),
  ('Ethiopia', 'ET', 'Ministry of Revenue', FALSE,
   TRUE, TRUE, 'TIN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567890'),
  ('Falkland Islands', 'FK', 'Falkland Islands Government Tax Office', FALSE,
   TRUE, TRUE, 'TIN', 'XXXXXXXXXXXXXXXX (alphanumeric up to 16 characters long)',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Faroe Islands', 'FO', 'TAKS', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'P-tal', 'DDMMYY-XXX',
   TRUE, FALSE, 'V-tal', '123456',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'MVG V-tal', '123456'),
  ('Fiji', 'FJ', 'Fiji Revenue and Customs Service', FALSE,
   TRUE, TRUE, 'TIN', '291-456-7830',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '291-456-7830'),
  ('Finland', 'FI', 'Finnish Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Identity Code', '131052-308T',
   TRUE, FALSE, 'Business ID', '1234567-8',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'ALV Number', '1234567-8'),
  ('France', 'FR', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('French Guiana', 'GF', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('French Polynesia', 'PF', 'Direction des impôts et des contributions publiques', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', 'SYYMMLLOOOKKK KK',
   TRUE, FALSE, 'SIREN', '123456',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'T123456, E123456, I991234'),
  ('French Southern Territories', 'TF', 'DGFiP', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Gabon', 'GA', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '1234567890123',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '1234567 0'),
  ('Gambia', 'GM', 'Gambia Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567890'),
  ('Georgia', 'GE', 'Revenue Service of Georgia', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Number', '12345678901',
   TRUE, FALSE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('Germany', 'DE', 'Federal Central Tax Office (BZSt), state tax authorities, municipal tax offices', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Steuer-ID', '12345678901',
   TRUE, FALSE, 'Steuernummer', '12/345/67890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'USt-IdNr.', 'DE123456789'),
  ('Ghana', 'GH', 'Ghana Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Ghanacard PIN', 'GHA-123456789-1',
   TRUE, FALSE, 'TIN', 'C0045678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'C0045678901'),
  ('Gibraltar', 'GI', 'Income Tax Office', FALSE,
   TRUE, TRUE, 'Taxpayer Reference Number', '55555, 666666',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Greece', 'GR', 'Independent Authority for Public Revenue (AADE/IAPR)', FALSE,
   TRUE, TRUE, 'AFM', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'EL123456789'),
  ('Greenland', 'GL', 'Greenland Tax Agency', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CPR Number', 'DDMMYY-1234',
   TRUE, FALSE, 'GER Number', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Grenada', 'GD', 'Inland Revenue Division', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456'),
  ('Guadeloupe', 'GP', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Guam', 'GU', 'Guam Department of Revenue and Taxation', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN/ITIN', '123-45-6789',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Guatemala', 'GT', 'Superintendencia de Administración Tributaria (SAT)', FALSE,
   TRUE, TRUE, 'CUI/NIT', '1234 56789 0101',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CUI/NIT', '1234 56789 0101'),
  ('Guernsey', 'GG', 'Guernsey Revenue Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SIN0', 'GY123456',
   TRUE, FALSE, 'TRN', '1X123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Guinea', 'GN', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIF', '123456789'),
  ('Guinea-Bissau', 'GW', 'Direcção Geral das Contribuições e Impostos (DGCI)', FALSE,
   TRUE, TRUE, 'NIF', '999999999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIF', '999999999'),
  ('Guyana', 'GY', 'Guyana Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIS', 'A-1234567, B-1234567',
   TRUE, FALSE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('Haiti', 'HT', 'Direction Générale des Impôts', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NINU', '1234567890',
   TRUE, FALSE, 'NIF', '123-456-789-0',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '123-456-789-0'),
  ('Heard Island and McDonald Islands', 'HM', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Holy See', 'VA', 'Directorate for the Economy, Governorate of Vatican City State', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, NULL, NULL),
  ('Honduras', 'HN', 'Revenue Administration Service (SAR)', FALSE,
   TRUE, TRUE, 'RTN', 'AA BB CC YYYY NNNN',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'RTN', 'AA BB CC YYYY NNNN'),
  ('Hong Kong', 'HK', 'Inland Revenue Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'HKID', 'A123456(7)',
   TRUE, FALSE, 'BRN', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, NULL, NULL),
  ('Hungary', 'HU', 'National Tax and Customs Administration (NAV)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Tax ID', '1234567890',
   TRUE, FALSE, 'Tax Number', '12345678-1-23',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'HU12345678'),
  ('Iceland', 'IS', 'Iceland Revenue and Customs (Skatturinn)', FALSE,
   TRUE, TRUE, 'Kennitala', '123456-7890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VSK Number', '123456'),
  ('India', 'IN', 'Income Tax Department (CBDT), Central Board of Indirect Taxes and Customs, state GST departments', FALSE,
   TRUE, TRUE, 'PAN', 'AFZPK7190K',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GSTIN', '22AAAAA0000A1Z5'),
  ('Indonesia', 'ID', 'Directorate General of Taxes', FALSE,
   TRUE, TRUE, 'NPWP', '01.234.567.8-901.000',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PKP Number', '01.234.567.8-901.000'),
  ('Iran', 'IR', 'Iranian National Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'National ID Number', '1234567890',
   TRUE, FALSE, 'Economic Code', '411 111 111 111',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Economic Code', '411 111 111 111'),
  ('Iraq', 'IQ', 'General Commission for Taxes', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'INID', '123456789012',
   TRUE, FALSE, 'TIN', '4444, 55555',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, NULL, NULL),
  ('Ireland', 'IE', 'Revenue Commissioners', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PPS Number', '1234567AB',
   TRUE, FALSE, 'Tax Reference Number', '1234567AB',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'IE1234567AB'),
  ('Isle of Man', 'IM', 'Isle of Man Income Tax Division, Customs and Excise Division', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual Tax Reference Number', 'H111111-11',
   TRUE, FALSE, 'Corporate Tax Reference Number', 'C333333-33',
   TRUE, FALSE, 'Partnership Tax Reference Number', 'X555555-55',
   TRUE, TRUE, 'VAT Number', 'GB 00x xxxx xx'),
  ('Israel', 'IL', 'Israel Tax Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'ID Number', '123456782',
   TRUE, FALSE, 'Tax File Number', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '000012345'),
  ('Italy', 'IT', 'Agenzia delle Entrate, Agenzia delle Dogane e dei Monopoli', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Codice Fiscale', 'RSSMRA80A01H501U',
   TRUE, FALSE, 'Partita IVA', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Partita IVA', 'IT12345678901'),
  ('Jamaica', 'JM', 'Tax Administration Jamaica', FALSE,
   TRUE, TRUE, 'TRN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TRN', '123456789'),
  ('Japan', 'JP', 'National Tax Agency, prefectural and municipal tax offices', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'My Number', '123 456 789 012',
   TRUE, FALSE, 'Corporate Number', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'JCT Number', 'T1234567890123'),
  ('Jersey', 'JE', 'Revenue Jersey, Jersey Customs and Immigration Service', FALSE,
   TRUE, TRUE, 'TIN', '100-100-1000',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST Number', '1234567'),
  ('Jordan', 'JO', 'Income and Sales Tax Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal TIN', '1234567890',
   TRUE, FALSE, 'Corporate TIN', '123456789012345',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Corporate TIN', '123456789012345'),
  ('Kazakhstan', 'KZ', 'State Revenue Committee of the Ministry of Finance', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IIN', '123 456 789 012',
   TRUE, FALSE, 'BIN', '123 456 789 012',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT BIN', '123 456 789 012'),
  ('Kenya', 'KE', 'Kenya Revenue Authority', FALSE,
   TRUE, TRUE, 'PIN', 'P000111111A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT PIN', 'P000111111A'),
  ('Kiribati', 'KI', 'Tax Division, Ministry of Finance and Economic Development', FALSE,
   TRUE, TRUE, 'TIN', 'xx. xxx. xxx/xxxx-xx',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, NULL, NULL),
  ('Kuwait', 'KW', 'Ministry of Finance, Tax Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Civil ID', '123 456 789 012',
   TRUE, FALSE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, NULL, NULL),
  ('Kyrgyzstan', 'KG', 'State Tax Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PIN', '12 345 678 901 234',
   TRUE, FALSE, 'TIN', '12 345 678 901 234',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12 345 678 901 234'),
  ('Laos', 'LA', 'Tax Department, Ministry of Finance', FALSE,
   TRUE, TRUE, 'TIN', '123456789-000',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789-000'),
  ('Latvia', 'LV', 'State Revenue Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Code', '010203-12345',
   TRUE, FALSE, 'Registration Number', '40001234567',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PVN Number', 'LV40001234567'),
  ('Lebanon', 'LB', 'Ministry of Finance, Revenue Directorate', FALSE,
   TRUE, TRUE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '123456789-601'),
  ('Lesotho', 'LS', 'Lesotho Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'National ID Number', '123456789012',
   TRUE, FALSE, 'TIN', '50012345',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '50012345'),
  ('Liberia', 'LR', 'Liberia Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '987654321',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST/VAT TIN', '987654321'),
  ('Libya', 'LY', 'Libyan Tax Authority', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Liechtenstein', 'LI', 'Liechtenstein Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'AHV Number', '123 456 789 012',
   TRUE, FALSE, 'UID', 'CHE123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '12345'),
  ('Lithuania', 'LT', 'State Tax Inspectorate under the Ministry of Finance', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal Code', '12345678901',
   TRUE, FALSE, 'Legal Entity Code', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PVM Code', 'LT123456789123'),
  ('Luxembourg', 'LU', 'Luxembourg Inland Revenue, Registration Duties, Estates and VAT Authority, Customs and Excise Agency', FALSE,
   TRUE, TRUE, 'Matricule', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'LU12345678'),
  ('Macao', 'MO', 'Financial Services Bureau', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BIR', '1234567(8)',
   TRUE, FALSE, 'Taxpayer Number', '8123456(7)',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Madagascar', 'MG', 'General Directorate of Taxes', FALSE,
   TRUE, TRUE, 'NIF', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '1234567890'),
  ('Malawi', 'MW', 'Malawi Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NID', '123456789012',
   TRUE, FALSE, 'TPIN', '88888888',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TPIN', '88888888'),
  ('Malaysia', 'MY', 'Inland Revenue Board of Malaysia, Royal Malaysian Customs Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal TIN', 'IG115002000',
   TRUE, FALSE, 'Business TIN', 'C20880050010',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SST TIN', 'A12-3456-78912345'),
  ('Maldives', 'MV', 'Maldives Inland Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NID', '1555550',
   TRUE, FALSE, 'TIN', '2555550ABC',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST TIN', '2123456GST789'),
  ('Mali', 'ML', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '999999999A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA NIF', '999999999A'),
  ('Malta', 'MT', 'Malta Tax and Customs Administration', FALSE,
   TRUE, TRUE, 'TIN', '0000999A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'MT12345678'),
  ('Marshall Islands', 'MH', 'Division of Revenue and Taxation, Ministry of Finance', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN', '04-XXXXXX',
   TRUE, FALSE, 'EIN', '08612-04',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Martinique', 'MQ', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Mauritania', 'MR', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NIF', '12345678'),
  ('Mauritius', 'MU', 'Mauritius Revenue Authority', FALSE,
   TRUE, TRUE, 'TAN', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TAN', '12345678'),
  ('Mayotte', 'YT', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Mexico', 'MX', 'Servicio de Administración Tributaria (SAT), state finance secretariats', FALSE,
   TRUE, TRUE, 'RFC', 'ABCD010203AB9',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RFC', 'ABC010203AB9'),
  ('Micronesia', 'FM', 'Division of Customs and Tax Administration, Department of Finance and Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN', 'AAA-GG-SSSS',
   TRUE, FALSE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Moldova', 'MD', 'State Tax Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IDNP', '1 234 567 890 123',
   TRUE, FALSE, 'IDNO', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '1234567'),
  ('Monaco', 'MC', 'Department of Tax Services', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, FALSE, 'NIS', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Mongolia', 'MN', 'General Department of Taxation', FALSE,
   TRUE, TRUE, 'TIN', '1234567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567'),
  ('Montenegro', 'ME', 'Tax Administration of Montenegro', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'JMBG', '1 234 567 890 123',
   TRUE, FALSE, 'PIB', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT PIB', '12345678'),
  ('Montserrat', 'MS', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'SSN', '666666',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Morocco', 'MA', 'General Tax Administration', FALSE,
   TRUE, TRUE, 'IF', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT IF', '12345678'),
  ('Mozambique', 'MZ', 'Mozambique Tax Authority (Autoridade Tributária de Moçambique)', FALSE,
   TRUE, TRUE, 'NUIT', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NUIT', '123456789'),
  ('Myanmar', 'MM', 'Internal Revenue Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NRC', '12/BAHANA(N)002332',
   TRUE, FALSE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Commercial Tax TIN', '123456789'),
  ('Namibia', 'NA', 'Namibia Revenue Agency (NamRA)', FALSE,
   TRUE, TRUE, 'TIN', '1234 5678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234 5678'),
  ('Nauru', 'NR', 'Nauru Revenue Office', FALSE,
   TRUE, TRUE, 'TIN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Nepal', 'NP', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'PAN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT PAN', '123456789'),
  ('Netherlands', 'NL', 'Netherlands Tax and Customs Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BSN', '123456789',
   TRUE, FALSE, 'RSIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'BTW-id', 'NL123456789B12'),
  ('New Caledonia', 'NC', 'Direction des Services Fiscaux', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TIN', '1234567',
   TRUE, FALSE, 'RIDET', '123456.001',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TGC RIDET', '123456.001'),
  ('New Zealand', 'NZ', 'Inland Revenue', FALSE,
   TRUE, TRUE, 'IRD Number', '123-456-789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST IRD', '123-456-789'),
  ('Nicaragua', 'NI', 'Dirección General de Ingresos (DGI)', FALSE,
   TRUE, TRUE, 'RUC', 'J1234567890123',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RUC', 'J1234567890123'),
  ('Niger', 'NE', 'Direction Générale des Impôts', FALSE,
   TRUE, TRUE, 'NIF', '4444, 55555',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IFU/TVA Number', '123456789ABC'),
  ('Nigeria', 'NG', 'Federal Inland Revenue Service, State Internal Revenue Services', FALSE,
   TRUE, TRUE, 'TIN', '12345678-0001',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12345678-0001'),
  ('Niue', 'NU', 'Revenue Management Division, Ministry of Finance', FALSE,
   TRUE, TRUE, 'TIN', '88-888-888, 999-999-999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NCR/IRD TIN', '88-888-888, 999-999-999'),
  ('Norfolk Island', 'NF', 'Australian Taxation Office', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TFN', '123456789',
   TRUE, FALSE, 'ABN', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST ABN', '12345678901'),
  ('North Korea', 'KP', 'Ministry of Finance', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('North Macedonia', 'MK', 'Public Revenue Office', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'EMBG', '1 234 567 890 123',
   TRUE, FALSE, 'EDB', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'MK1234567890123'),
  ('Northern Mariana Islands', 'MP', 'Division of Revenue and Taxation', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN/ITIN', '123-45-6789',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Norway', 'NO', 'Norwegian Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Fødselsnummer', '12345678901',
   TRUE, FALSE, 'Organisation Number', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'MVA Number', '123456789MVA'),
  ('Oman', 'OM', 'Tax Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, FALSE, 'TIN', '1234567',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'OM1234567890'),
  ('Pakistan', 'PK', 'Federal Board of Revenue, provincial revenue authorities', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CNIC', '12345-1234567-1',
   TRUE, FALSE, 'NTN', '1234567',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'STRN', '1234567, 12345-1234567-1'),
  ('Palau', 'PW', 'Bureau of Revenue and Taxation', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PGST TIN', '123456'),
  ('Palestine', 'PS', 'Ministry of Finance', FALSE,
   TRUE, TRUE, 'PS-TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT PS-TIN', '123456789'),
  ('Panama', 'PA', 'Dirección General de Ingresos (DGI)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal RUC', '8-100-678 DV: 90',
   TRUE, FALSE, 'Business RUC', '155986022-2-2019 DV: 12',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RUC', '8-100-678 DV: 90, 155986022-2-2019 DV: 12'),
  ('Papua New Guinea', 'PG', 'Internal Revenue Commission', FALSE,
   TRUE, TRUE, 'TIN', 'XX-XXXXXX-X',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST TIN', 'XX-XXXXXX-X'),
  ('Paraguay', 'PY', 'Dirección Nacional de Ingresos Tributarios (DNIT)', FALSE,
   TRUE, TRUE, 'RUC', '666666-X, 7777777-X, 88888888-X, 999999999-X',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'RUC/IVA Number', '800XXXXX-X'),
  ('Peru', 'PE', 'Superintendencia Nacional de Aduanas y de Administración Tributaria (SUNAT)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'DNI', '12345678',
   TRUE, FALSE, 'RUC', '12345678901',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RUC', '12345678901'),
  ('Philippines', 'PH', 'Bureau of Internal Revenue, Bureau of Customs', FALSE,
   TRUE, TRUE, 'TIN', '123-456-789-000',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123-456-789-000'),
  ('Pitcairn', 'PN', 'Pitcairn Islands Office', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Poland', 'PL', 'National Revenue Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PESEL/NIP', '12345678901',
   TRUE, FALSE, 'NIP', '1234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'PL1234567890'),
  ('Portugal', 'PT', 'Tax and Customs Authority', FALSE,
   TRUE, TRUE, 'NIF', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'PT123456789'),
  ('Puerto Rico', 'PR', 'Puerto Rico Department of Treasury (Departamento de Hacienda)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN', '123-45-6789',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IVU Number', '7777777-4444'),
  ('Qatar', 'QA', 'General Tax Authority', FALSE,
   TRUE, TRUE, 'TIN', '123-456-7890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Republic of the Congo', 'CG', 'Direction Générale des Impôts et des Domaines', FALSE,
   TRUE, TRUE, 'NIU', '12345678901234567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIU TVA', '12345678901234567'),
  ('Réunion', 'RE', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Romania', 'RO', 'National Agency for Fiscal Administration (ANAF)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CNP', '1 234 567 890 123',
   TRUE, FALSE, 'CIF', '1234567891',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'RO1234567891'),
  ('Russia', 'RU', 'Federal Tax Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual INN', 'NNNNXXXXXXCC',
   TRUE, FALSE, 'Business INN', 'NNNNXXXXXC',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'KPP', 'NNNN00XXX'),
  ('Rwanda', 'RW', 'Rwanda Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('Saint Barthélemy', 'BL', 'Collectivité de Saint-Barthélemy', FALSE,
   TRUE, TRUE, 'SIREN', '999 999 999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'St Helena Revenue Office', FALSE,
   TRUE, TRUE, 'TIN', '1234567890123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Saint Kitts and Nevis', 'KN', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'Base TIN', '55555',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '555551'),
  ('Saint Lucia', 'LC', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Saint Martin (French part)', 'MF', 'Collectivité de Saint-Martin, Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Saint Pierre and Miquelon', 'PM', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Numéro fiscal', '12 34 56 789 012 34',
   TRUE, FALSE, 'SIREN', '123 456 789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA Number', 'FRAB123456789'),
  ('Saint Vincent and the Grenadines', 'VC', 'Inland Revenue Department', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12345601'),
  ('Samoa', 'WS', 'Ministry for Revenue', FALSE,
   TRUE, TRUE, 'TIN', '999999999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAGST TIN', '999999999'),
  ('San Marino', 'SM', 'Tax Office, Department of Finance', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSI Number', '123456789',
   TRUE, FALSE, 'COE', 'SM12345',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Sao Tome and Principe', 'ST', 'Tax Directorate', FALSE,
   TRUE, TRUE, 'NIF', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIF IVA', '123456789'),
  ('Saudi Arabia', 'SA', 'Zakat, Tax and Customs Authority (ZATCA)', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, FALSE, 'TIN', '3123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT VRN', '333 456 789 012 345'),
  ('Senegal', 'SN', 'Direction générale des Impôts et des Domaines (DGID)', FALSE,
   TRUE, TRUE, 'NINEA', '12345672A2',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT NINEA', '12345672A2'),
  ('Serbia', 'RS', 'Tax Administration, Ministry of Finance', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'JMBG', '1 234 567 890 123',
   TRUE, FALSE, 'PIB', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT PIB', '123456789'),
  ('Seychelles', 'SC', 'Seychelles Revenue Commission', FALSE,
   TRUE, TRUE, 'TIN', '1234567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567'),
  ('Sierra Leone', 'SL', 'National Revenue Authority', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual TIN', '1234567-9',
   TRUE, FALSE, 'Business TIN', '12345678-0',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST TIN', '1234567-9, 12345678-0'),
  ('Singapore', 'SG', 'Inland Revenue Authority of Singapore', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NRIC/FIN', 'S1234567D',
   TRUE, FALSE, 'UEN', '12345678A, 202412345Z, T24LL1234G',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST Number', 'YYYYnnnnnX, nnnnnnnnX, MnnnnnnnnX, MRnnnnnnnnA'),
  ('Sint Maarten (Dutch part)', 'SX', 'Tax Administration, Government of Sint Maarten', FALSE,
   TRUE, TRUE, 'CRIB Number', '123.456.789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'CRIB/BBO Number', '123.456.789'),
  ('Slovakia', 'SK', 'Financial Administration of the Slovak Republic', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Rodné číslo', '123456/7890',
   TRUE, FALSE, 'DIČ', '1234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IČ DPH', 'SK1234567890'),
  ('Slovenia', 'SI', 'Financial Administration of the Republic of Slovenia', FALSE,
   TRUE, TRUE, 'TIN', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'SI12345678'),
  ('Solomon Islands', 'SB', 'Inland Revenue Division', FALSE,
   TRUE, TRUE, 'TIN', '7777777, 88888888, 999999999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax TIN', '7777777, 88888888, 999999999'),
  ('Somalia', 'SO', 'Inland Revenue Department, Ministry of Finance of the Federal Republic of Somalia', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Tirsi Aqoonsi', '12345678901',
   TRUE, FALSE, 'TIN', 'C123456789R, C1234567890R, C12345678901R',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax TIN', 'C123456789R, C1234567890R, C12345678901R'),
  ('South Africa', 'ZA', 'South African Revenue Service', FALSE,
   TRUE, TRUE, 'Income Tax Number', '0123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '4123456789'),
  ('South Georgia and the South Sandwich Islands', 'GS', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('South Korea', 'KR', 'National Tax Service', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Resident Registration Number', '123456-1234567',
   TRUE, FALSE, 'BRN', '123-45-67890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT BRN', '123-45-67890'),
  ('South Sudan', 'SS', 'South Sudan Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '123-345-567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax TIN', '123-345-567'),
  ('Spain', 'ES', 'Agencia Tributaria, regional and foral tax authorities', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIF/NIE', '12345678Z / X1234567L',
   TRUE, FALSE, 'NIF/CIF', 'A1234567X',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'IVA Number', 'ESA1234567Z'),
  ('Sri Lanka', 'LK', 'Inland Revenue Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NIC', 'YYYY DDD NNNNN, 853400937V',
   TRUE, FALSE, 'TIN', 'YYYY DDD NNNNN, 853400937V',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '123456789-7000'),
  ('Sudan', 'SD', 'Sudan Tax Chamber', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personal TIN', 'XXXX-YYMMDD-123',
   TRUE, FALSE, 'Business TIN', 'XXX-YYMMDD-123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax TIN', 'XXX-YYMMDD-123, XXXX-YYMMDD-123'),
  ('Suriname', 'SR', 'Tax Department, Ministry of Finance and Planning', FALSE,
   TRUE, TRUE, 'FIN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT FIN', '1234567890'),
  ('Svalbard and Jan Mayen', 'SJ', 'Norwegian Tax Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Fødselsnummer', '12345678901',
   TRUE, FALSE, 'Organisation Number', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'MVA Number', '123456789MVA'),
  ('Sweden', 'SE', 'Swedish Tax Agency', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Personnummer', '123456-7890',
   TRUE, FALSE, 'Organisationsnummer', '123456-7890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'SE123456789001'),
  ('Switzerland', 'CH', 'Swiss Federal Tax Administration, cantonal and communal tax administrations', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'AHV Number', '756.1234.5678.97',
   TRUE, FALSE, 'UID', 'CHE-123.456.789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'CHE-123.456.789 MWST'),
  ('Syria', 'SY', 'General Commission for Taxes and Fees', FALSE,
   TRUE, TRUE, 'National Number', '12345678901',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Sales Tax Number', '12345678901'),
  ('Taiwan', 'TW', 'Ministry of Finance, National Taxation Bureaus, local tax bureaus', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'National ID Number', 'A123456789',
   TRUE, FALSE, 'Uniform Business Number', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT UBN', '12345678'),
  ('Tajikistan', 'TJ', 'Tax Committee under the Government of the Republic of Tajikistan', FALSE,
   TRUE, TRUE, 'TIN', '123456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456789'),
  ('Tanzania', 'TZ', 'Tanzania Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '12345678A',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '12345678A'),
  ('Thailand', 'TH', 'Revenue Department, Excise Department, Customs Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'National ID Number', '1 234 567 890 123',
   TRUE, FALSE, 'TIN', '1 234 567 890 123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1 234 567 890 123'),
  ('Timor-Leste', 'TL', 'Autoridade Tributária Timor-Leste (ATTL)', FALSE,
   TRUE, TRUE, 'TIN', '1234567',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Togo', 'TG', 'Office Togolais des Recettes (OTR)', FALSE,
   TRUE, TRUE, 'TIF', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA TIF', '1234567890'),
  ('Tokelau', 'TK', 'Government of Tokelau, Department of Finance', FALSE,
   TRUE, TRUE, 'IRD Number', '123-456-789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Tonga', 'TO', 'Ministry of Revenue and Customs', FALSE,
   TRUE, TRUE, 'TIN', '123456',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Consumption Tax TIN', '123456'),
  ('Trinidad and Tobago', 'TT', 'Inland Revenue Division', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual BIR Number', '123456789-0',
   TRUE, FALSE, 'Business BIR Number', '512345678-0',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT BIR Number', '512345678-0'),
  ('Tunisia', 'TN', 'Direction Générale des Impôts', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual IF/TIN', '1234567A',
   TRUE, FALSE, 'Business IF/TIN', '5432167A/XXX/000',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT IF/TIN', '5432167A/XXX/000'),
  ('Türkiye', 'TR', 'Revenue Administration', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TCKN', '12345678901',
   TRUE, FALSE, 'VKN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '1234567890'),
  ('Turkmenistan', 'TM', 'Tax Department of the Ministry of Finance and Economy of Turkmenistan', FALSE,
   TRUE, TRUE, 'HSB/TIN', '123456789012',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT HSB/TIN', '123456789012'),
  ('Turks and Caicos Islands', 'TC', 'Revenue Department', FALSE,
   TRUE, TRUE, 'TCI NIB', 'AB123456C',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Tuvalu', 'TV', 'Inland Revenue and Customs Department', FALSE,
   TRUE, TRUE, 'TIN', '999999999',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TCT Number', '55555'),
  ('Uganda', 'UG', 'Uganda Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '1014751879',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1014751879'),
  ('Ukraine', 'UA', 'State Tax Service of Ukraine, State Customs Service of Ukraine', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'RNTRC', '1234567890',
   TRUE, FALSE, 'EDRPOU', '12345678',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '123 456 789 012'),
  ('United Arab Emirates', 'AE', 'Federal Tax Authority, emirate-level finance and tax authorities', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, FALSE, 'Corporate Tax Registration Number', '100 2345 6789 0123',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TRN', '123 456 789 012 345'),
  ('United Kingdom', 'GB', 'HM Revenue & Customs, Welsh Revenue Authority, Revenue Scotland', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'NINO', 'AB123456C',
   TRUE, FALSE, 'UTR', '1234567890',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', 'GB123456789'),
  ('United States', 'US', 'Internal Revenue Service, state departments of revenue and taxation', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN/ITIN', '123-45-6789, 912-34-5678',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, 'Unknown', 'Unknown'),
  ('United States Minor Outlying Islands', 'UM', 'N/A', TRUE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Uruguay', 'UY', 'Dirección General Impositiva', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Identity Card', '12345678',
   TRUE, FALSE, 'RUT', '123 456 789 012',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT RUT', '123 456 789 012'),
  ('Uzbekistan', 'UZ', 'Tax Committee of the Republic of Uzbekistan', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'PINFL', '12 345 678 901 234',
   TRUE, FALSE, 'STIR', '123456789',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Number', '123 456 789 012'),
  ('Vanuatu', 'VU', 'Customs and Inland Revenue Department', FALSE,
   TRUE, TRUE, 'TIN', '123456, 1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '123456, 1234567890'),
  ('Venezuela', 'VE', 'Servicio Nacional Integrado de Administración Aduanera y Tributaria (SENIAT)', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Individual RIF', 'V-12345678-9',
   TRUE, FALSE, 'Business RIF', 'J-12345678-9',
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'Business RIF', 'J-12345678-9'),
  ('Vietnam', 'VN', 'General Department of Taxation', FALSE,
   TRUE, TRUE, 'Tax Code', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT Tax Code', '1234567890'),
  ('Virgin Islands, British', 'VG', 'Inland Revenue Department', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Virgin Islands, U.S.', 'VI', 'Virgin Islands Bureau of Internal Revenue', FALSE,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'SSN/ITIN', '123-45-6789',
   TRUE, FALSE, 'EIN', '12-3456789',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Wallis and Futuna', 'WF', 'Direction générale des Finances publiques (DGFiP)', FALSE,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL),
  ('Western Sahara', 'EH', 'General Tax Administration (Morocco-administered areas)', FALSE,
   TRUE, TRUE, 'IF/TIN', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'TVA IF/TIN', '12345678'),
  ('Yemen', 'YE', 'Yemen Tax Authority', FALSE,
   TRUE, TRUE, 'TIN', '12345678',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'GST TIN', '12345678'),
  ('Zambia', 'ZM', 'Zambia Revenue Authority', FALSE,
   TRUE, TRUE, 'TPIN', '1004751879',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TPIN', '1004751879'),
  ('Zimbabwe', 'ZW', 'Zimbabwe Revenue Authority', FALSE,
   TRUE, TRUE, 'TIN', '1234567890',
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   FALSE, FALSE, NULL, NULL,
   TRUE, TRUE, 'VAT TIN', '1234567890')

ON CONFLICT (country_code) DO UPDATE SET
  country_name                = EXCLUDED.country_name,
  tax_authority               = EXCLUDED.tax_authority,
  is_unverifiable             = EXCLUDED.is_unverifiable,
  generic_id_corp_display     = EXCLUDED.generic_id_corp_display,
  generic_id_indiv_display    = EXCLUDED.generic_id_indiv_display,
  generic_id_name             = EXCLUDED.generic_id_name,
  generic_id_format           = EXCLUDED.generic_id_format,
  individual_id_corp_display  = EXCLUDED.individual_id_corp_display,
  individual_id_indiv_display = EXCLUDED.individual_id_indiv_display,
  individual_id_name          = EXCLUDED.individual_id_name,
  individual_id_format        = EXCLUDED.individual_id_format,
  business_id_corp_display    = EXCLUDED.business_id_corp_display,
  business_id_indiv_display   = EXCLUDED.business_id_indiv_display,
  business_id_name            = EXCLUDED.business_id_name,
  business_id_format          = EXCLUDED.business_id_format,
  partnership_id_corp_display  = EXCLUDED.partnership_id_corp_display,
  partnership_id_indiv_display = EXCLUDED.partnership_id_indiv_display,
  partnership_id_name          = EXCLUDED.partnership_id_name,
  partnership_id_format        = EXCLUDED.partnership_id_format,
  vat_id_corp_display         = EXCLUDED.vat_id_corp_display,
  vat_id_indiv_display        = EXCLUDED.vat_id_indiv_display,
  vat_id_name                 = EXCLUDED.vat_id_name,
  vat_id_format               = EXCLUDED.vat_id_format;
